spring:
  application:
    name: downloader-service
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:filedownloader}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      max-lifetime: 1200000
      pool-name: FileDownloaderHikariPool
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        default_schema: ${DOWNLOADER_SERVICE_SCHEMA:downloader_service}
        format_sql: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
  liquibase:
    enabled: true
    default-schema: ${spring.jpa.properties.hibernate.default_schema}
    change-log: classpath:db/changelog/db.changelog-master.yaml
    drop-first: false
    parameters:
      schema: ${spring.jpa.properties.hibernate.default_schema}
      extension-schema: pg_catalog

server:
  port: ${DOWNLOADER_SERVICE_PORT:8085}
  forward-headers-strategy: framework

springdoc:
  cache:
    disabled: true

openapi:
  base-url: ${GATEWAY_PUBLIC_URL}

logging:
  level:
    org.springframework.web.client: trace
    com.filedownloader: INFO

security:
  cors:
    allowed-origins: ${ALLOWED_ORIGINS}
---

spring:
  config:
    activate:
      on-profile: sit
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:filedownloader}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      max-lifetime: 1200000
      pool-name: FileDownloaderHikariPool
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    drop-first: false

server:
  port: ${DOWNLOADER_SERVICE_PORT:8085}
  forward-headers-strategy: framework

springdoc:
  cache:
    disabled: true

openapi:
  base-url: ${GATEWAY_PUBLIC_URL}

security:
  cors:
    allowed-origins: ${ALLOWED_ORIGINS}
