/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/file-description": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create file description */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/file-description/all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get all file descriptions by filter */
        post: operations["getAllFileDescriptions"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/file-description/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get file description by id */
        get: operations["getById"];
        put?: never;
        post?: never;
        /** Delete file description */
        delete: operations["delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/file-description/{id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download ready file */
        get: operations["download"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description File description create request */
        CreateFileDto: {
            /** @description Original file name */
            filename: string;
            /** @description Source URL */
            sourceUrl: string;
        };
        /** @description File description response */
        FileDescriptionDto: {
            /** Format: uuid */
            id?: string;
            /** @description Original file name */
            filename: string;
            /** @description Local path or S3 key */
            storagePath: string;
            /** @description Source URL */
            sourceUrl: string;
            /**
             * @description File description status
             * @enum {string}
             */
            status?: "PENDING" | "HEADER_PROCESSING_PENDING" | "HEADER_PROCESSING" | "DOWNLOADING_CHUNKS" | "ASSEMBLE_CHUNKS" | "DOWNLOAD_COMPLETED" | "FAILED";
            /**
             * Format: int64
             * @description Total file size in bytes
             */
            totalSize: number;
            /** @description MIME type */
            mimeType: string;
            /** @description Checksum of whole file */
            checksum?: string;
            /** @description Additional metadata */
            metadata?: {
                [key: string]: Record<string, never>;
            };
            /** @description Error message */
            errorMessage?: string;
            /**
             * Format: int32
             * @description Percentage of downloading
             */
            percentage?: number;
            /** Format: date-time */
            createdDate?: string;
            /** Format: date-time */
            updatedDate?: string;
        };
        /** @description File description filter */
        FileDescriptionFilter: {
            /** @description Set of identifiers of entities */
            ids?: string[];
            /** @description File name */
            filename?: string;
            /** @description Source URL */
            sourceUrl?: string;
            /**
             * @description Description status
             * @enum {string}
             */
            status?: "PENDING" | "HEADER_PROCESSING_PENDING" | "HEADER_PROCESSING" | "DOWNLOADING_CHUNKS" | "ASSEMBLE_CHUNKS" | "DOWNLOAD_COMPLETED" | "FAILED";
            /** @description MIME type */
            mimeType?: string;
        };
        PageMetadata: {
            /** Format: int64 */
            size?: number;
            /** Format: int64 */
            number?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int64 */
            totalPages?: number;
        };
        PagedModelFileDescriptionDto: {
            content?: components["schemas"]["FileDescriptionDto"][];
            page?: components["schemas"]["PageMetadata"];
        };
        /** @description File chunk response */
        FileChunkDto: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            fileId?: string;
            /** Format: int32 */
            chunkIndex?: number;
            /** Format: int64 */
            startByte?: number;
            /** Format: int64 */
            endByte?: number;
            /** Format: int64 */
            currentSize?: number;
            /** @enum {string} */
            status?: "PENDING" | "UPLOADING" | "COMPLETED" | "FAILED";
            workerId?: string;
            sourceUrl?: string;
            storagePath?: string;
            /** Format: int32 */
            retryCount?: number;
            /** Format: date-time */
            lastHeartbeat?: string;
            /** Format: date-time */
            completedAt?: string;
            errorMessage?: string;
        };
        /** @description File description response with chunks */
        FileDescriptionWithChunksDto: {
            /** Format: uuid */
            id?: string;
            filename?: string;
            storagePath?: string;
            sourceUrl?: string;
            /** @enum {string} */
            status?: "PENDING" | "HEADER_PROCESSING_PENDING" | "HEADER_PROCESSING" | "DOWNLOADING_CHUNKS" | "ASSEMBLE_CHUNKS" | "DOWNLOAD_COMPLETED" | "FAILED";
            /** Format: int64 */
            totalSize?: number;
            mimeType?: string;
            checksum?: string;
            metadata?: {
                [key: string]: Record<string, never>;
            };
            errorMessage?: string;
            /** Format: date-time */
            createdDate?: string;
            /** Format: date-time */
            updatedDate?: string;
            /**
             * Format: int32
             * @description Percentage of downloading
             */
            percentage?: number;
            /** @description File chunks */
            chunks?: components["schemas"]["FileChunkDto"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateFileDto"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileDescriptionDto"];
                };
            };
        };
    };
    getAllFileDescriptions: {
        parameters: {
            query?: {
                /** @description Zero-based page index (0..N) */
                page?: number;
                /** @description The size of the page to be returned */
                size?: number;
                /** @description Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported. */
                sort?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["FileDescriptionFilter"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedModelFileDescriptionDto"];
                };
            };
        };
    };
    getById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileDescriptionWithChunksDto"];
                };
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    download: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                    "application/json": string;
                };
            };
        };
    };
}
