apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keycloak-db
spec:
  selector:
    matchLabels:
      app: keycloak-db
  serviceName: keycloak-db-service
  replicas: 1
  template:
    metadata:
      labels:
        app: keycloak-db
    spec:
      containers:
        - name: keycloak-db
          image: postgres:17-alpine
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: filedownloader-config
                  key: KEYCLOAK_POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: filedownloader-config
                  key: KEYCLOAK_POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: filedownloader-secrets
                  key: KEYCLOAK_POSTGRES_PASSWORD
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: keycloak-db-data
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "keycloak"]
            initialDelaySeconds: 5
            periodSeconds: 5
  volumeClaimTemplates:
    - metadata:
        name: keycloak-db-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-db-service
spec:
  selector:
    app: keycloak-db
  ports:
    - port: 5432
      targetPort: 5432
  clusterIP: None